// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbxHgMM3_lb7bfbJUHSknCsdt7pitm9Is82FH-AtUQsWxJGOOzsr1Q6jRIBCZWX29BUHBA/exec";
